---
# We now call the satellite_operations.installer role to run the installer
- ansible.builtin.include_role:
    name: "redhat.satellite_operations.installer"
  vars:
    satellite_installer_scenario: "satellite"
    satellite_installer_options: "{{ sat_installer_options }}"

