---
# This play will configure the mandatory Content Views for the lab.
# Create requires the cv loop variable.
- name: Creating the specified content views
  include_tasks: create_cv.yml
  loop: "{{ cvs_optional }}"
  loop_control:
    loop_var: cv

# Publish requires the cv loop variable.
- name: Publish the specified content views
  include_tasks: publish_cv_version.yml
  loop: "{{ cvs_optional }}"
  loop_control:
    loop_var: cv

