---
# Download the specified manifest from the portal
#
- name: Download the specified manifest
  redhat_manifest:
    portal: "{{ manifest_portal_url }}"
    username: "{{ manifest_cdn_username }}"
    password: "{{ manifest_cdn_password }}"
    validate_certs: "{{ manifest_validate_certs }}"
    name: "{{ manifest_name }}"
    path: "{{ manifest_path }}"
